
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL1BiasRom(
  input  [5:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      6'd0: data = 32'h00000616;
      6'd1: data = 32'h000000f3;
      6'd2: data = 32'h0000017f;
      6'd3: data = 32'h0000016a;
      6'd4: data = 32'hfffffe7e;
      6'd5: data = 32'h00000022;
      6'd6: data = 32'hfffffec1;
      6'd7: data = 32'h000002a6;
      6'd8: data = 32'hfffffde0;
      6'd9: data = 32'h0000019c;
      6'd10: data = 32'hffffff5d;
      6'd11: data = 32'h00000051;
      6'd12: data = 32'hfffffef7;
      6'd13: data = 32'h000000f2;
      6'd14: data = 32'h000001f9;
      6'd15: data = 32'h0000066a;
      6'd16: data = 32'h00000303;
      6'd17: data = 32'h00000476;
      6'd18: data = 32'h00000261;
      6'd19: data = 32'hfffffce6;
      6'd20: data = 32'hffffff0f;
      6'd21: data = 32'h000002ad;
      6'd22: data = 32'hfffffe85;
      6'd23: data = 32'hfffffda4;
      6'd24: data = 32'h0000019c;
      6'd25: data = 32'h00000016;
      6'd26: data = 32'hfffffe81;
      6'd27: data = 32'h0000061f;
      6'd28: data = 32'h000001a7;
      6'd29: data = 32'h000002d5;
      6'd30: data = 32'h000000b3;
      6'd31: data = 32'h00000495;
      6'd32: data = 32'hfffffa5b;
      6'd33: data = 32'hfffffcd6;
      6'd34: data = 32'hfffffbf9;
      6'd35: data = 32'h00000166;
      6'd36: data = 32'h000002f6;
      6'd37: data = 32'h0000040c;
      6'd38: data = 32'h000004a1;
      6'd39: data = 32'hfffffec8;
      6'd40: data = 32'h0000036c;
      6'd41: data = 32'hfffffede;
      6'd42: data = 32'h00000340;
      6'd43: data = 32'hffffff39;
      6'd44: data = 32'h00000246;
      6'd45: data = 32'hfffff61c;
      6'd46: data = 32'hfffff98f;
      6'd47: data = 32'h000006d8;
      6'd48: data = 32'h0000008a;
      6'd49: data = 32'h000007bc;
      6'd50: data = 32'h00000413;
      6'd51: data = 32'hfffffd47;
      6'd52: data = 32'h00000592;
      6'd53: data = 32'hfffffe87;
      6'd54: data = 32'h0000008e;
      6'd55: data = 32'h0000029d;
      6'd56: data = 32'h00000209;
      6'd57: data = 32'hfffffdb8;
      6'd58: data = 32'h000000a8;
      6'd59: data = 32'h000001fb;
      6'd60: data = 32'h000006df;
      6'd61: data = 32'hfffffcd9;
      6'd62: data = 32'h00000131;
      6'd63: data = 32'hffffff65;
      default: data = 32'h0;
    endcase
  end
endmodule

