
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL2BiasRom(
  input  [4:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      5'd0: data = 32'h000001bb;
      5'd1: data = 32'h00000152;
      5'd2: data = 32'h000000cf;
      5'd3: data = 32'h000000cf;
      5'd4: data = 32'h000000d1;
      5'd5: data = 32'h0000010a;
      5'd6: data = 32'h000000a8;
      5'd7: data = 32'h00000040;
      5'd8: data = 32'h000000d6;
      5'd9: data = 32'hffffff42;
      5'd10: data = 32'hffffffc6;
      5'd11: data = 32'h00000075;
      5'd12: data = 32'h00000037;
      5'd13: data = 32'h0000003b;
      5'd14: data = 32'h000000ab;
      5'd15: data = 32'h000001b9;
      5'd16: data = 32'hffffff53;
      5'd17: data = 32'h0000018e;
      5'd18: data = 32'h0000010e;
      5'd19: data = 32'h00000064;
      5'd20: data = 32'h000000c5;
      5'd21: data = 32'h0000005a;
      5'd22: data = 32'h00000086;
      5'd23: data = 32'h00000054;
      5'd24: data = 32'h00000073;
      5'd25: data = 32'h000000fe;
      5'd26: data = 32'h0000011c;
      5'd27: data = 32'h000000c3;
      5'd28: data = 32'h00000120;
      5'd29: data = 32'h00000022;
      5'd30: data = 32'hffffff47;
      5'd31: data = 32'h00000028;
      default: data = 32'h0;
    endcase
  end
endmodule

