
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL3WeightRom(
  input  [3:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      4'd0: data = 32'hd9ddea34;
      4'd1: data = 32'hd9eb21e0;
      4'd2: data = 32'h2cedf72c;
      4'd3: data = 32'h35e3232b;
      4'd4: data = 32'h23263a5d;
      4'd5: data = 32'h7e31270f;
      4'd6: data = 32'h29ebe0ed;
      4'd7: data = 32'hef540233;
      4'd8: data = 32'h10261cdb;
      4'd9: data = 32'h0920f127;
      4'd10: data = 32'hc11befd3;
      4'd11: data = 32'hc41bc6ed;
      4'd12: data = 32'hd6e2bd99;
      4'd13: data = 32'h81ced0f0;
      4'd14: data = 32'hc71c0d25;
      4'd15: data = 32'h249f15c8;
      default: data = 32'h0;
    endcase
  end
endmodule

