
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL3WeightRom(
  input  [3:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      4'd0: data = 32'hd7e5e752;
      4'd1: data = 32'hd3e628da;
      4'd2: data = 32'h2deea236;
      4'd3: data = 32'h43e42735;
      4'd4: data = 32'h18275e73;
      4'd5: data = 32'h4f222b1b;
      4'd6: data = 32'h29e3d9ec;
      4'd7: data = 32'hef490227;
      4'd8: data = 32'h0d1f20c0;
      4'd9: data = 32'h0928ee2f;
      4'd10: data = 32'hbc1c3ec9;
      4'd11: data = 32'hb519bce8;
      4'd12: data = 32'he0e19781;
      4'd13: data = 32'h9fdec9e3;
      4'd14: data = 32'hc3260f2a;
      4'd15: data = 32'h27a61bd4;
      default: data = 32'h0;
    endcase
  end
endmodule

