
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL1BiasRom(
  input  [5:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      6'd0: data = 32'h00000321;
      6'd1: data = 32'h0000008b;
      6'd2: data = 32'h00000469;
      6'd3: data = 32'hfffffeef;
      6'd4: data = 32'h000000ef;
      6'd5: data = 32'h000002e9;
      6'd6: data = 32'hffffff47;
      6'd7: data = 32'h000001a9;
      6'd8: data = 32'hfffffe42;
      6'd9: data = 32'h000000c6;
      6'd10: data = 32'h0000008b;
      6'd11: data = 32'h0000008e;
      6'd12: data = 32'hffffff9d;
      6'd13: data = 32'h00000166;
      6'd14: data = 32'h00000345;
      6'd15: data = 32'h00000176;
      6'd16: data = 32'hffffffc7;
      6'd17: data = 32'h000002bf;
      6'd18: data = 32'h00000323;
      6'd19: data = 32'hffffff94;
      6'd20: data = 32'h000000c3;
      6'd21: data = 32'h00000183;
      6'd22: data = 32'hffffff2e;
      6'd23: data = 32'h00000309;
      6'd24: data = 32'h0000024a;
      6'd25: data = 32'hfffffc00;
      6'd26: data = 32'hfffffe68;
      6'd27: data = 32'h0000054e;
      6'd28: data = 32'hffffffc7;
      6'd29: data = 32'h00000286;
      6'd30: data = 32'h00000088;
      6'd31: data = 32'h00000480;
      6'd32: data = 32'hfffffdd6;
      6'd33: data = 32'hfffffed8;
      6'd34: data = 32'h00000099;
      6'd35: data = 32'h000000d6;
      6'd36: data = 32'h0000021a;
      6'd37: data = 32'h000002b5;
      6'd38: data = 32'h000003c9;
      6'd39: data = 32'hfffffe86;
      6'd40: data = 32'h000000af;
      6'd41: data = 32'h0000000a;
      6'd42: data = 32'h0000020f;
      6'd43: data = 32'h000000c9;
      6'd44: data = 32'h000005b2;
      6'd45: data = 32'hfffff939;
      6'd46: data = 32'hfffffd5f;
      6'd47: data = 32'hffffffc2;
      6'd48: data = 32'h00000442;
      6'd49: data = 32'h00000520;
      6'd50: data = 32'h00000329;
      6'd51: data = 32'hfffffd38;
      6'd52: data = 32'h00000484;
      6'd53: data = 32'hfffffe4d;
      6'd54: data = 32'hffffff79;
      6'd55: data = 32'h00000395;
      6'd56: data = 32'hfffffa57;
      6'd57: data = 32'hfffffe05;
      6'd58: data = 32'hfffffe9f;
      6'd59: data = 32'hffffff12;
      6'd60: data = 32'h0000049e;
      6'd61: data = 32'hfffffb6b;
      6'd62: data = 32'h00000126;
      6'd63: data = 32'h00000116;
      default: data = 32'h0;
    endcase
  end
endmodule

