
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL2BiasRom(
  input  [4:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      5'd0: data = 32'h0000027a;
      5'd1: data = 32'h00000145;
      5'd2: data = 32'h0000009b;
      5'd3: data = 32'h00000111;
      5'd4: data = 32'h00000052;
      5'd5: data = 32'h0000018d;
      5'd6: data = 32'h00000089;
      5'd7: data = 32'h00000014;
      5'd8: data = 32'h00000143;
      5'd9: data = 32'hffffff38;
      5'd10: data = 32'hffffffe6;
      5'd11: data = 32'h000001b3;
      5'd12: data = 32'h00000094;
      5'd13: data = 32'h00000024;
      5'd14: data = 32'h00000093;
      5'd15: data = 32'h00000228;
      5'd16: data = 32'hffffff0f;
      5'd17: data = 32'h000001f4;
      5'd18: data = 32'h00000133;
      5'd19: data = 32'h000000ce;
      5'd20: data = 32'h00000172;
      5'd21: data = 32'h00000091;
      5'd22: data = 32'h000000c5;
      5'd23: data = 32'h00000172;
      5'd24: data = 32'h0000006b;
      5'd25: data = 32'h000000f7;
      5'd26: data = 32'h000000d1;
      5'd27: data = 32'h0000011c;
      5'd28: data = 32'h00000218;
      5'd29: data = 32'hffffffea;
      5'd30: data = 32'h000000f8;
      5'd31: data = 32'h00000014;
      default: data = 32'h0;
    endcase
  end
endmodule

