
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL2BiasRom(
  input  [4:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      5'd0: data = 32'h0000012b;
      5'd1: data = 32'h000000d7;
      5'd2: data = 32'h00000058;
      5'd3: data = 32'h000000b8;
      5'd4: data = 32'h00000059;
      5'd5: data = 32'h000000d3;
      5'd6: data = 32'h0000005a;
      5'd7: data = 32'h00000006;
      5'd8: data = 32'h00000080;
      5'd9: data = 32'h000000a8;
      5'd10: data = 32'hffffffec;
      5'd11: data = 32'h000000b6;
      5'd12: data = 32'hffffffec;
      5'd13: data = 32'h0000004d;
      5'd14: data = 32'h0000005d;
      5'd15: data = 32'h000000e2;
      5'd16: data = 32'h00000053;
      5'd17: data = 32'h00000115;
      5'd18: data = 32'h000000ba;
      5'd19: data = 32'h00000047;
      5'd20: data = 32'h000000c7;
      5'd21: data = 32'h0000006a;
      5'd22: data = 32'h00000075;
      5'd23: data = 32'hffffff63;
      5'd24: data = 32'h0000001b;
      5'd25: data = 32'h000000b3;
      5'd26: data = 32'h00000092;
      5'd27: data = 32'h00000044;
      5'd28: data = 32'h00000112;
      5'd29: data = 32'hffffffff;
      5'd30: data = 32'hffffff7a;
      5'd31: data = 32'h0000000e;
      default: data = 32'h0;
    endcase
  end
endmodule

