
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL3BiasRom(
  input  [0:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      1'd0: data = 32'hffffff36;
      1'd1: data = 32'h00000033;
      default: data = 32'h0;
    endcase
  end
endmodule

