
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL1BiasRom(
  input  [5:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      6'd0: data = 32'h00000110;
      6'd1: data = 32'hfffffdfe;
      6'd2: data = 32'h00000243;
      6'd3: data = 32'h000001ed;
      6'd4: data = 32'h0000074b;
      6'd5: data = 32'h000006d1;
      6'd6: data = 32'hfffffde7;
      6'd7: data = 32'h00000119;
      6'd8: data = 32'hfffffe8e;
      6'd9: data = 32'h00000171;
      6'd10: data = 32'hfffffe92;
      6'd11: data = 32'h000001a9;
      6'd12: data = 32'hfffffd24;
      6'd13: data = 32'h00000265;
      6'd14: data = 32'h000004be;
      6'd15: data = 32'h000006ee;
      6'd16: data = 32'h0000058d;
      6'd17: data = 32'h0000047f;
      6'd18: data = 32'h000003ed;
      6'd19: data = 32'hfffffa56;
      6'd20: data = 32'h000000d4;
      6'd21: data = 32'h000002fe;
      6'd22: data = 32'hfffffe2c;
      6'd23: data = 32'h00000282;
      6'd24: data = 32'hfffffdab;
      6'd25: data = 32'hfffff8d4;
      6'd26: data = 32'hfffffe96;
      6'd27: data = 32'h00000a7a;
      6'd28: data = 32'h00000421;
      6'd29: data = 32'h000002e8;
      6'd30: data = 32'h0000008b;
      6'd31: data = 32'h00000a09;
      6'd32: data = 32'hfffff9c1;
      6'd33: data = 32'hfffffd4e;
      6'd34: data = 32'h000001a4;
      6'd35: data = 32'h00000033;
      6'd36: data = 32'h0000043d;
      6'd37: data = 32'h00000467;
      6'd38: data = 32'h0000060b;
      6'd39: data = 32'hfffffe6c;
      6'd40: data = 32'h00000246;
      6'd41: data = 32'hffffff9a;
      6'd42: data = 32'h000006b1;
      6'd43: data = 32'h00000a5e;
      6'd44: data = 32'h00000486;
      6'd45: data = 32'hfffff6ff;
      6'd46: data = 32'h0000014f;
      6'd47: data = 32'hffffff9e;
      6'd48: data = 32'h00000414;
      6'd49: data = 32'h000005c6;
      6'd50: data = 32'h000003aa;
      6'd51: data = 32'hfffffd0a;
      6'd52: data = 32'h00000995;
      6'd53: data = 32'hfffffd58;
      6'd54: data = 32'h0000009d;
      6'd55: data = 32'h00000441;
      6'd56: data = 32'hfffffb10;
      6'd57: data = 32'hfffffea3;
      6'd58: data = 32'hfffff7d7;
      6'd59: data = 32'hffffff61;
      6'd60: data = 32'h00000743;
      6'd61: data = 32'hfffffbc5;
      6'd62: data = 32'h00000086;
      6'd63: data = 32'h00000063;
      default: data = 32'h0;
    endcase
  end
endmodule

