
// Generated by CIRCT firtool-1.62.0
module RadarQMLPL3WeightRom(
  input  [3:0] addr,
  output reg [31:0] data
);

  always @* begin
    case (addr)
      4'd0: data = 32'hdbd2e95a;
      4'd1: data = 32'hd2e923e2;
      4'd2: data = 32'h34de4731;
      4'd3: data = 32'h2fe63523;
      4'd4: data = 32'h22205674;
      4'd5: data = 32'h7c2a1d22;
      4'd6: data = 32'h25c7dae9;
      4'd7: data = 32'heff9fe19;
      4'd8: data = 32'h0b321eb7;
      4'd9: data = 32'h0d24f227;
      4'd10: data = 32'hb72c9ccd;
      4'd11: data = 32'hca18b0f8;
      4'd12: data = 32'hd6e8a082;
      4'd13: data = 32'h81d5d8dc;
      4'd14: data = 32'hc941112b;
      4'd15: data = 32'h25f81ce2;
      default: data = 32'h0;
    endcase
  end
endmodule

